package com.garbuzov.diary.command;

public enum CommandType {

    SIGN_UP, PARENT_REGISTRATION, SUBJECT_ADD, GRADE_ADD, FIND_ALL_GRADE,
    STUDENT_ADD, FIND_ALL_STUDENT, FIND_ALL_SUBJECT, TEACHER_REGISTRATION,
    FIND_ALL_TEACHER, FIND_ALL_PARENT, PARENT_DELETION, TEACHER_DELETION,
    STUDENT_UPDATE, GRADE_UPDATE, SUBJECT_UPDATE, LANGUAGE_SWITCH, GRADE_FOR_TEACHER,
    LESSON_ADD, LESSON_DELETION, FIND_JOURNAL, TIMETABLE_ADD, TIMETABLE_DELETION,
    MARK_ADD, HOMEWORK_ADD, BACK_JOURNAL, FORWARD_JOURNAL, FIND_DIARY, BACK_DIARY,
    FORWARD_DIARY, FIND_HOMEWORK, BACK_HOMEWORK, FORWARD_HOMEWORK
}
